### ISSUE TITLE
[BUG] Connection Closed when sending message to groups 

### ISSUE THREAD

**Issue by luispimenta** [bahriid/bailleys-api-v2#1]
When trying to send any messages to groups, the request takes a long time and returns this error. how can i resolve this?

`"err":{"type":"Error","message":"Connection Closed","stack":"Error: Connection Closed\n    at sendRawMessage (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)\n    at sendNode (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)\n    at query (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:137:15)\n    at groupQuery (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)\n    at Object.groupMetadata (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)\n    at jidExists (/var/app/current/dist/wa.js:251:41)\n    at send (/var/app/current/dist/controllers/message.js:37:49)\n    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/app/current/node_modules/express/lib/router/route.js:144:13)\n    at validate (/var/app/current/dist/middlewares/session-validator.js:7:5)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Closed"},"headers":{}}},"msg":"An error occured during message send Error: Connection Closed"}`

I have tried `defaultQueryTimeoutMs: undefined` and `defaultQueryTimeoutMs: 0`

but nothing worked

everything was ok since yesterday, and it stopped without any updates or any adjustments

my makeWASocket

```
const socket = makeWASocket({
    printQRInTerminal: true,
    browser: Browsers.ubuntu('Chrome'),
    generateHighQualityLinkPreview: true,
    ...socketConfig,
    auth: {
      creds: state.creds,
      keys: makeCacheableSignalKeyStore(state.keys, logger),
    },
    logger,
    defaultQueryTimeoutMs: 0,
    shouldIgnoreJid: (jid) => isJidBroadcast(jid),
    getMessage: async (key) => {
      const data = await prisma.message.findFirst({
        where: { remoteJid: key.remoteJid!, id: key.id!, sessionId },
      });
      return (data?.message || undefined) as proto.IMessage | undefined;
    },
  });

```

**Comment by sersawy** [comment]
@luispimenta did you solve this?
